### ISSUE TITLE
Add JavaScript build process

### ISSUE THREAD

**Issue by nuest** [ultical/ultical#22]
Adding a JavaScript build process allows to add useful features such as code checking/linters and minification of files, and also adding license headers to the created files (which was the reason this came up in #18).

**Which system should we use?** On the list of candidates there are
- grunt
- gulp
- npm

A very interesting read on the topic (including the discussions): http://blog.keithcirkel.co.uk/why-we-should-stop-using-grunt.

I would probably go with grunt since I've done minimal things with it before, but since I won't become the main JavaScript developer, I'd like to hear other opinions on this.
## Tasks
- [ ] minify JS
- [ ] add license headers to JS

**Comment by bastrapp** [comment]
Very interesting read, indeed. As I read this and some follow-ups I thought it would be great to give npm a shot. I would then try-out switching away from bower to npm for frontend package handling as well. But then reading even more got me thinking. Seems that complex tasks are better handled by grunt or gulp while npm is easy for easy stuff... 

In the end: If you set up a working system I am happy with either. In the beginning I will only be 'using' it anyways and (hopefully) not working myself into the details...

**Comment by nuest** [comment]
I'll give npm a try over the weekend, mostly following http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/

**Comment by nuest** [comment]
@bastrapp What OS are you guys on? Windows, Mac, Linux?

**Comment by bastrapp** [comment]
I am using mac...
Am 27.02.2016 12:34 schrieb "Daniel Nüst" notifications@github.com:

**Comment by bslbckr** [comment]
@nuest I'm on Linux. But I guess that, the sooner or later, portability might become an issue if we go for npm (I'm looking at you, windows). Anyway, I totally agree that we should start with npm. 

In a different project I started playing around a little bit with angular, npm and browserify. For the moment I am working with a package.json like this:

``` json
{
    "name": "Foo",
    "version": "0.0.1",
    "description": "",
    "main": "src/main/javascript/app.js",
    "dependencies": {
        "angular": "~1.5.0"
    },
    "devDependencies": {
        "browserify": "~13.0.0",
        "jslint": "^0.9.6",
        "minifyify": "~7.3.2"
    },
    "scripts": {
        "lint": "jslint --node src/main/javascript/app.js",
        "copy-resources": "cp src/main/javascript/index.html target/index.html",
        "prebuild": "npm run-script copy-resources",
        "build": "browserify src/main/javascript/app.js -d -p [minifyify --map target/app.js.map --output target/app.js.map] > target/app.min.js",
        "predebug-build": "npm run-script copy-resources",
        "debug-build": "browserify src/main/javascript/app.js > target/app.min.js",
        "test": "echo \"Error: no test specified\" && exit 1"
    },
    "author": "",
    "license": "MIT"
}
```

However, as I decided to use browserify, I had to make use `require('module')` inside my `app.js`. Otherwise, browserify was not able to include also angular within the package. As I was working on a little toy-example, including angular in the final .js-file was not an issue. However, for ultical I could imagine that we only bundle our own js-files together and, e.g. load the third party libs from a cdn?

**Comment by bslbckr** [comment]
For adding a banner I found this browserify transformer: https://www.npmjs.com/package/bannerify

**Comment by nuest** [comment]
Thanks for the pointers - keep them coming :-). I'll post updates here as soon as I have them, but first got to take advantage of the nice weather :sunny:

**Comment by nuest** [comment]
Well, JavaScript is really not my strongest side, but I learn stuff, so that's good.

### Short progress report
- removed all bower and grunt - stuff (the latter never comitted)
- updated README.md
- re-install all dependencies to have more concrete versions (no `*`)
- configured [JSHint](http://stackoverflow.com/questions/6803305/should-i-use-jslint-or-jshint-javascript-validation)
- moved all lot of files to `/public`
- changed quite a few things in `index.html`
  - using CDNs for libs is not required anymore since using browserify
  - removed `<base href="/ultical-web">` > this most probably breaks the server deployment! will figure that out once the app works in development...
  - configure browserify (see http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support)
  - since browserify is used, the order of loading JS files is not fixed, so we must _properly configure module dependencies_ (which is a good thing! use dependency injection instead of file order..) **work in progress**

### Open tasks
- [ ] fix JS loading and Angular module dependencies
- [ ] try npm version patch, npm version minor and npm version major
- [ ] try out LiveReload > http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/
- [ ] try to figure out a way to split up app bundle and dependency bundle - I've tried a bunch of tutorials, probably need a fresh set of eyes...
  - http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support
  - https://github.com/sogko/gulp-recipes/tree/master/browserify-separating-app-and-vendor-bundles

It would be great if you could check out my branch and see if you get the Angular app working. I am no Angular expert, I'm afraid. Will have to put this aside for some time now.

**Comment by nuest** [comment]
Trying to fix this in https://github.com/nuest/ultical/commit/ccac680930e6b2cd5715d76457b6172b8bae4357

**Comment by bastrapp** [comment]
`<base href="/">` is needed for html5mode allowing for url rewrites (urls without #)

I didn't find a way yet to parameterize the path

**Comment by nuest** [comment]
OK, thanks for the clarification. Then I'll need to figure that one out :-)

**Comment by nuest** [comment]
Ups, sorry. Wrong button. Monday.

**Comment by nuest** [comment]
Maybe I should take a look at webpack - could make things easier, or more complex: https://webpack.github.io/

**Comment by bslbckr** [comment]
What would the benefit of webpack be? If I understand the task correctly we "simply" have to bundle our javascript and deploy it together with some pics and html-templates, right? 
Don't get me wrong, if there's a good reason for webpack or any other tool, we should go with it. Otherwise, I would prefer to keep things as simple as possible

**Comment by nuest** [comment]
I agree with you - the thing is that right now, it does not work :-) And webpack seems to work well with Angular. It'll be a few more weekends before I can look into this again, but the task list above is current.

**Comment by bslbckr** [comment]
That's a good reason :)

**Comment by bastrapp** [comment]
As Angular2 is rising into productive use we should keep in mind, that for this new version a build process is mandatory. They use [systemjs](https://github.com/systemjs/systemjs) in their basic tutorials but also refer to webpack as being a great tool... so I think one of those should be used.

**Comment by bslbckr** [comment]
Did I understand correctly, that systemjs is transpiling TypeScript sources directly in the browser when they were loaded?

**Comment by nuest** [comment]
Do you guys think about moving to Angular 2? Surely would be fun...
